version: '3.8'

networks:
  main_network:
    driver: bridge

services:
  # Database
  main_db:
    image: postgres:latest
    container_name: main_db_container
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    networks:
      - main_network

  # Main Service backend
  main_service_be:
    image: wisnup001binus/hackglobal-newbier:2.0
    container_name: main_service_container
    environment:
      PORT: 8000
      DATABASE_URL: postgres://postgres:123@main_db:5432/test?sslmode=disable
      GEMINI_KEY: ""
      CHATGPT_KEY: ""
    networks:
      - main_network
    ports:
      - "8000:8000"
    depends_on:
      - main_db

  main_service_fe:
    image: wisnup001binus/hackglobal-newbier-fe:2.0
    container_name: main_service_container_fe
    environment:
      VITE_REACT_API_URL: http://13.75.124.106:8000
    networks:
      - main_network
    ports:
      - "80:4000"